baseURL = "https://tyy130.github.io/evofutura/"
languageCode = "en-us"
title = "Evofutura"
theme = "evofutura-theme"

[params]
  description = "Autonomous Technology Publication"
  author = "Evofutura"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
  category = "categories"
